import Head from 'next/head';
import Sidebar from '../partials/Sidebar';
import Header from '../partials/Header';
import Footer from '../partials/Footer';
import Journal from '../journal';
import { useState } from 'react';
import { useApplicationData } from '../../hooks/useApplicationData';

export default function Layout({ children, title }) {
  const { toggleJournal, day, today, journalOpen, handleSetDay, handleCalNav } = useApplicationData();

  const [darkMode, setDarkMode] = useState(false);

  const bodyClass = () => {
    if (darkMode) {
      return 'dark';
    } else {
      return 'light';
    }
  }

  const handleDarkMode = () => {
    setDarkMode(darkMode ? false : true);
  }

  return(<>
      <Head>
        <title>{title} | ActiveJourney</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className={bodyClass}>
        <div className='flex h-screen flex-col bg-white text-body dark:bg-dark-14 dark:text-dark-body {styles.main}'>
          <div className='flex-grow overflow-auto'>
            <div className='flex flex-col order-2 sm:flex-row sm:order-1'>
              <Sidebar 
                setDarkMode={handleDarkMode}
                toggleJournal={toggleJournal}
              />
              <main
                id='section-main'
                className='bg-slate-100 relative w-full h-auto min-h-screen sm:ml-[75px]'
              >
                <div className='flex h-full flex-col p-8 mb-6'>
                  <Header pageTitle={title} />
                    {children}
                  <Footer />
                </div>
              </main>
            </div>
          </div>
          {journalOpen && (
            <Journal
              day={day}
              today={today}
              setDay={handleSetDay}
              onClose={toggleJournal}
              handleCalNav={handleCalNav}
            />
          )}
        </div>
      </div>
  </>)
}