import { useState } from 'react'
import '../styles/globals.css'
import '../styles/tailwind.css'
import { Inter } from 'next/font/google'
import Head from 'next/head'
import Sidebar from '../components/partials/Sidebar'
import Journal from '../components/journal'
import Footer from '../components/partials/Footer'

export default function App ({ Component, pageProps }) {  
  return (
    <>
      <Head>
        <title>ActiveJourney</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Component {...pageProps} />
    </>
  )
}
