import { useState, useEffect } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import { PrismaClient } from '@prisma/client'
import Sidebar from '../components/partials/_sidebar'
import Header from '../components/partials/_header'
import Footer from '../components/partials/_footer'

const inter = Inter({ subsets: ['latin'] })

export default function Settings(props) {
  return (
    <>
      <Head>
        <title>Journal Listing | ActiveJourney</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex h-screen flex-col bg-white text-body dark:bg-dark-14 dark:text-dark-body {styles.main}">
        
        <div className="flex-grow overflow-auto">
          <div className="flex flex-col order-2 sm:flex-row sm:order-1 h-full">
            <Sidebar />
            <main id="section-main" className="bg-slate-100 relative sm:mx-auto w-full h-full max-w-200 overflow-auto">
              <div className="flex h-full flex-col p-8 mb-6">
                <Header
                  pageTitle="Journal Listing"
                  userName={props.user.first_name}
                />
                <section className="mx-3 bg-white rounded-lg p-6 overflow-auto">
                  <table className="table-auto border-collapse border border-slate-300 w-full mb-4 text-sm sm:text-base">
                    <thead>
                      <tr className='bg-blue-900 text-white'>
                        <th className="text-left p-2 border border-slate-200">Day</th>
                        <th className="text-left p-2 border border-slate-200">Water Intake</th>
                        <th className="text-left p-2 border border-slate-200">Mood</th>
                        <th className="text-left p-2 border border-slate-200">Activity</th>
                        <th className="text-left p-2 border border-slate-200">Sleep</th>
                        <th className="text-left p-2 border border-slate-200">Sleep Quality</th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr className="">
                        <td  className="p-2 border border-slate-200">March 31, 2023</td>
                        <td  className="p-2 border border-slate-200">6 cups</td>
                        <td  className="p-2 border border-slate-200">10</td>
                        <td  className="p-2 border border-slate-200">30 min</td>
                        <td  className="p-2 border border-slate-200">8 hours</td>
                        <td  className="p-2 border border-slate-200">10</td>
                      </tr>
                      <tr>
                        <td className="p-2 border border-slate-200">March 30, 2023</td>
                        <td className="p-2 border border-slate-200">5 cups</td>
                        <td className="p-2 border border-slate-200">9</td>
                        <td className="p-2 border border-slate-200">30 min</td>
                        <td className="p-2 border border-slate-200">8 hours</td>
                        <td  className="p-2 border border-slate-200">10</td>
                      </tr>
                      <tr>
                        <td className="p-2 border border-slate-200">March 29, 2023</td>
                        <td className="p-2 border border-slate-200">9 cups</td>
                        <td className="p-2 border border-slate-200">9</td>
                        <td className="p-2 border border-slate-200">30 min</td>
                        <td className="p-2 border border-slate-200">8 hours</td>
                        <td  className="p-2 border border-slate-200">8/10</td>
                      </tr>
                    </tbody>
                  </table> 
                </section>
                
                
                <Footer />
              </div>
            </main>
          </div>
        </div>
      </div>
    </>
  )
}


// Fetch all posts (in /pages/index.tsx)
export async function getServerSideProps() {
  const prisma = new PrismaClient()

  const user = await prisma.user.findUnique({
    where: {
      id: 1,
    }
  })

  return {
    props : { user }
  }
}
